<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>

                    <!-- Log In Drop Down -->
                    <!-- http://mifsud.me/adding-dropdown-login-form-bootstraps-navbar/ -->
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation()->menu()->renderMenu('navigation', array('ulClass' => 'nav')); ?>
                        <ul class="nav pull-right">
                          <?php if ($this->zfcUserIdentity()) : ?>
                          <li>
                            <a href="/user">
                            <?php echo sprintf($this->translate('Signed in as %s'), $this->escapeHtml($this->zfcUserDisplayName())) ?>
                            </a>
                            </li>
                            <li>
                                <a href="/user/logout"><?php echo $this->translate('Log out'); ?></a>
                            </li>
                          <?php else :?>
                              <li><a href="/user/register"><?php echo $this->translate('Register') ?></a></li>
                              <li class="divider-vertical"></li>
                              <li class="dropdown">
                                 <a class="dropdown-toggle" href="#" data-toggle="dropdown"><?php echo $this->translate('Sign In') ?><strong class="caret"></strong></a>
                                 <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                                 <?php echo $this->zFcUserLoginWidget(); ?>
                                </div>
                              </li>
                          <?php endif; ?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
